"""
Diagnostic sweep for ALSS mode/tau behavior.

Purpose
-------
This script tests whether ALSS performance is sensitive to:
- alss_mode: zero vs ar1
- alss_tau: shrinkage strength

It is intended for diagnostics only. Results generated by this script are not
paper-ready unless rerun with a validated protocol and sufficient Monte Carlo
trials.

Recommended first run from repository root:

    $env:PYTHONPATH = "$(Get-Location)\\src;$(Get-Location)"
    python tools\\diagnose_alss_sweep.py --trials 10 --output-dir "$env:TEMP\\mimo_alss_diag_trial10"

The output CSV should be written outside the repository, typically under $env:TEMP.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment
from scipy.stats import t as t_dist
from scipy.stats import ttest_rel

# ---------------------------------------------------------------------
# Make repository imports work when script is run directly from tools/
# ---------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"

for path in (SRC_DIR, PROJECT_ROOT):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)

from core.radarpy.algorithms.coarray_music import estimate_doa_coarray_music  # noqa: E402
from core.radarpy.signal.doa_sim_core import simulate_snapshots  # noqa: E402
from core.radarpy.signal.mutual_coupling import generate_mcm  # noqa: E402


def get_array_positions(array_type: str, n_sensors: int = 7) -> np.ndarray:
    """Return array positions in half-wavelength index units."""
    array_type = array_type.upper()

    if array_type == "Z5":
        if n_sensors == 7:
            return np.array([0, 5, 8, 11, 14, 17, 21], dtype=float)
        positions = [0, 5, 8]
        for _ in range(3, n_sensors):
            positions.append(positions[-1] + 3)
        return np.array(positions, dtype=float)

    if array_type == "Z1":
        if n_sensors == 7:
            return np.array([0, 1, 4, 9, 10, 11, 12], dtype=float)
        return np.array([0, 1, 4] + list(range(9, 9 + n_sensors - 3)), dtype=float)

    if array_type == "ULA":
        return np.arange(n_sensors, dtype=float)

    raise ValueError(f"Unsupported array_type for this diagnostic script: {array_type}")


def compute_rmse(estimated: np.ndarray, true_doas: np.ndarray) -> float:
    """Compute assignment-aware DOA RMSE."""
    if len(estimated) != len(true_doas):
        return float("inf")

    cost = np.abs(true_doas[:, None] - estimated[None, :])
    row_ind, col_ind = linear_sum_assignment(cost)
    errors = true_doas[row_ind] - estimated[col_ind]
    return float(np.sqrt(np.mean(errors**2)))


def confidence_interval(values: Iterable[float], confidence: float = 0.95) -> tuple[float, float, float]:
    """Return mean and t-based confidence interval."""
    arr = np.asarray(list(values), dtype=float)
    arr = arr[np.isfinite(arr)]

    if len(arr) == 0:
        return float("nan"), float("nan"), float("nan")

    mean = float(np.mean(arr))

    if len(arr) < 2:
        return mean, float("nan"), float("nan")

    std = float(np.std(arr, ddof=1))
    sem = std / np.sqrt(len(arr))
    alpha = 1.0 - confidence
    t_crit = float(t_dist.ppf(1.0 - alpha / 2.0, df=len(arr) - 1))

    return mean, mean - t_crit * sem, mean + t_crit * sem


def run_one_trial(
    *,
    positions: np.ndarray,
    true_doas: np.ndarray,
    wavelength: float,
    snr_db: float,
    snapshots: int,
    coupling_matrix: np.ndarray | None,
    alss_enabled: bool,
    alss_mode: str,
    alss_tau: float,
    alss_core_l: int,
    seed: int,
) -> tuple[float, float]:
    """Run one DOA trial and return RMSE and runtime in ms."""
    d_phys = 0.5
    positions_meters = positions * d_phys

    x_snapshots, _, _ = simulate_snapshots(
        sensor_positions=positions_meters,
        wavelength=wavelength,
        doas_deg=true_doas,
        snr_db=snr_db,
        snapshots=snapshots,
        seed=seed,
        coupling_matrix=coupling_matrix,
    )

    start = time.time()

    estimated_doas, _ = estimate_doa_coarray_music(
        X=x_snapshots,
        positions=positions,
        d_phys=d_phys,
        wavelength=wavelength,
        K=len(true_doas),
        scan_deg=(-60, 60, 0.1),
        alss_enabled=alss_enabled,
        alss_mode=alss_mode,
        alss_tau=alss_tau,
        alss_coreL=alss_core_l,
    )

    runtime_ms = (time.time() - start) * 1000.0
    rmse = compute_rmse(estimated_doas, true_doas)

    return rmse, runtime_ms


def run_diagnostic(args: argparse.Namespace) -> pd.DataFrame:
    """Run baseline plus ALSS mode/tau diagnostic sweep."""
    positions = get_array_positions(args.array, args.n_sensors)
    true_doas = np.array(args.true_doas, dtype=float)
    wavelength = 1.0

    rows: list[dict[str, object]] = []

    print("=" * 72)
    print("ALSS DIAGNOSTIC SWEEP")
    print("=" * 72)
    print(f"Array: {args.array}")
    print(f"Positions: {positions.tolist()}")
    print(f"True DOAs: {true_doas.tolist()}")
    print(f"SNR values: {args.snrs}")
    print(f"Coupling values: {args.couplings}")
    print(f"Snapshots: {args.snapshots}")
    print(f"Trials: {args.trials}")
    print(f"Modes: {args.modes}")
    print(f"Tau values: {args.taus}")
    print(f"CoreL: {args.core_l}")
    print()

    for coupling_c1 in args.couplings:
        if coupling_c1 > 0:
            coupling_matrix = generate_mcm(
                len(positions),
                positions,
                model="exponential",
                c1=float(coupling_c1),
            )
        else:
            coupling_matrix = None

        for snr_db in args.snrs:
            print(f"\nConfig: c1={coupling_c1}, SNR={snr_db} dB, M={args.snapshots}")

            baseline_rmse: list[float] = []
            baseline_runtime: list[float] = []

            for trial in range(args.trials):
                seed = args.seed + trial
                rmse, runtime_ms = run_one_trial(
                    positions=positions,
                    true_doas=true_doas,
                    wavelength=wavelength,
                    snr_db=float(snr_db),
                    snapshots=args.snapshots,
                    coupling_matrix=coupling_matrix,
                    alss_enabled=False,
                    alss_mode="zero",
                    alss_tau=0.0,
                    alss_core_l=args.core_l,
                    seed=seed,
                )
                baseline_rmse.append(rmse)
                baseline_runtime.append(runtime_ms)

            base_mean, base_ci_low, base_ci_high = confidence_interval(baseline_rmse)

            rows.append(
                {
                    "Array": args.array,
                    "Coupling_c1": coupling_c1,
                    "SNR_dB": snr_db,
                    "Snapshots": args.snapshots,
                    "Trials": args.trials,
                    "Mode": "baseline",
                    "Tau": 0.0,
                    "CoreL": args.core_l,
                    "RMSE": base_mean,
                    "RMSE_CI_Low": base_ci_low,
                    "RMSE_CI_High": base_ci_high,
                    "Improvement_%": 0.0,
                    "P_Value": np.nan,
                    "Harmlessness_%": 100.0,
                    "Runtime_ms": float(np.mean(baseline_runtime)),
                }
            )

            print(f"  Baseline: RMSE={base_mean:.4f} deg")

            for mode in args.modes:
                for tau in args.taus:
                    alss_rmse: list[float] = []
                    alss_runtime: list[float] = []

                    for trial in range(args.trials):
                        seed = args.seed + trial
                        rmse, runtime_ms = run_one_trial(
                            positions=positions,
                            true_doas=true_doas,
                            wavelength=wavelength,
                            snr_db=float(snr_db),
                            snapshots=args.snapshots,
                            coupling_matrix=coupling_matrix,
                            alss_enabled=True,
                            alss_mode=mode,
                            alss_tau=float(tau),
                            alss_core_l=args.core_l,
                            seed=seed,
                        )
                        alss_rmse.append(rmse)
                        alss_runtime.append(runtime_ms)

                    alss_mean, alss_ci_low, alss_ci_high = confidence_interval(alss_rmse)
                    improvement = 100.0 * (base_mean - alss_mean) / base_mean if base_mean > 0 else 0.0

                    if len(baseline_rmse) >= 2:
                        _, p_value = ttest_rel(baseline_rmse, alss_rmse)
                    else:
                        p_value = np.nan

                    harmlessness = 100.0 * np.mean(np.asarray(alss_rmse) <= np.asarray(baseline_rmse))

                    rows.append(
                        {
                            "Array": args.array,
                            "Coupling_c1": coupling_c1,
                            "SNR_dB": snr_db,
                            "Snapshots": args.snapshots,
                            "Trials": args.trials,
                            "Mode": mode,
                            "Tau": tau,
                            "CoreL": args.core_l,
                            "RMSE": alss_mean,
                            "RMSE_CI_Low": alss_ci_low,
                            "RMSE_CI_High": alss_ci_high,
                            "Improvement_%": improvement,
                            "P_Value": float(p_value),
                            "Harmlessness_%": harmlessness,
                            "Runtime_ms": float(np.mean(alss_runtime)),
                        }
                    )

                    print(
                        f"  {mode:>4s}, tau={tau:<4}: "
                        f"RMSE={alss_mean:.4f} deg, "
                        f"Improvement={improvement:+.2f}%, "
                        f"p={p_value:.4f}, "
                        f"Harmless={harmlessness:.1f}%"
                    )

    return pd.DataFrame(rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Diagnose ALSS mode/tau sensitivity.")

    parser.add_argument("--array", type=str, default="Z5", choices=["Z5", "Z1", "ULA"])
    parser.add_argument("--n-sensors", type=int, default=7)
    parser.add_argument("--true-doas", nargs="+", type=float, default=[15.0, -20.0])
    parser.add_argument("--snrs", nargs="+", type=float, default=[5.0, 10.0, 15.0])
    parser.add_argument("--couplings", nargs="+", type=float, default=[0.0, 0.3])
    parser.add_argument("--snapshots", type=int, default=64)
    parser.add_argument("--trials", type=int, default=10)
    parser.add_argument("--modes", nargs="+", type=str, default=["zero", "ar1"], choices=["zero", "ar1"])
    parser.add_argument("--taus", nargs="+", type=float, default=[0.1, 0.25, 0.5, 1.0])
    parser.add_argument("--core-l", type=int, default=3)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--output-dir",
        type=str,
        default=os.path.join(os.environ.get("TEMP", "."), "mimo_alss_diagnostics"),
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results_df = run_diagnostic(args)

    csv_path = output_dir / "alss_mode_tau_diagnostic.csv"
    results_df.to_csv(csv_path, index=False)

    print("\n" + "=" * 72)
    print("[SUCCESS] Diagnostic results saved")
    print(f"CSV: {csv_path}")
    print("=" * 72)

    # Show best non-baseline row per coupling/SNR configuration.
    non_baseline = results_df[results_df["Mode"] != "baseline"].copy()
    if not non_baseline.empty:
        best = (
            non_baseline.sort_values("Improvement_%", ascending=False)
            .groupby(["Coupling_c1", "SNR_dB"], as_index=False)
            .first()
        )

        print("\nBest ALSS setting per configuration:")
        print(
            best[
                [
                    "Coupling_c1",
                    "SNR_dB",
                    "Mode",
                    "Tau",
                    "RMSE",
                    "Improvement_%",
                    "P_Value",
                    "Harmlessness_%",
                ]
            ].to_string(index=False)
        )


if __name__ == "__main__":
    main()