"""
Summarize ALSS diagnostic sweep results.

Purpose
-------
This tool reads the CSV generated by:

    tools/diagnose_alss_sweep.py

and computes a robust selection summary for each ALSS parameter pair:

    (Mode, Tau)

The scoring rule follows the draft ALSS parameter-selection protocol:

    Score = mean(Improvement_%) - 0.5 * abs(min(Worst_Improvement_Pct, 0))

A candidate is rejected if:
- worst-case improvement is below the configured degradation threshold
- average harmlessness is below the configured harmlessness threshold

Example
-------
Run from repository root:

    python tools\\summarize_alss_diagnostics.py `
        --input "$env:TEMP\\mimo_alss_diag_trial10\\alss_mode_tau_diagnostic.csv" `
        --output "$env:TEMP\\mimo_alss_diag_trial10\\alss_selection_summary.csv"
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REQUIRED_COLUMNS = {
    "Mode",
    "Tau",
    "Improvement_%",
    "Harmlessness_%",
    "RMSE",
    "Coupling_c1",
    "SNR_dB",
    "Trials",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize ALSS mode/tau diagnostic sweep results."
    )

    parser.add_argument(
        "--input",
        required=True,
        type=str,
        help="Input CSV generated by tools/diagnose_alss_sweep.py.",
    )

    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Output CSV path for the summarized parameter-selection table. "
            "If omitted, writes alss_selection_summary.csv next to the input file."
        ),
    )

    parser.add_argument(
        "--worst-degradation-threshold",
        type=float,
        default=-20.0,
        help="Reject candidates whose worst-case Improvement_% is below this value.",
    )

    parser.add_argument(
        "--min-average-harmlessness",
        type=float,
        default=70.0,
        help="Reject candidates whose average Harmlessness_%% is below this value.",
    )

    return parser.parse_args()


def validate_input(df: pd.DataFrame, input_path: Path) -> None:
    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        missing_text = ", ".join(missing)
        raise ValueError(f"Input file {input_path} is missing required columns: {missing_text}")

    if df.empty:
        raise ValueError(f"Input file {input_path} is empty.")

    non_baseline = df[df["Mode"].astype(str).str.lower() != "baseline"]
    if non_baseline.empty:
        raise ValueError("Input file contains no non-baseline ALSS rows to summarize.")


def summarize_diagnostics(
    df: pd.DataFrame,
    worst_degradation_threshold: float,
    min_average_harmlessness: float,
) -> pd.DataFrame:
    working = df.copy()

    working["Mode"] = working["Mode"].astype(str)
    working["Tau"] = pd.to_numeric(working["Tau"], errors="coerce")
    working["Improvement_%"] = pd.to_numeric(working["Improvement_%"], errors="coerce")
    working["Harmlessness_%"] = pd.to_numeric(working["Harmlessness_%"], errors="coerce")
    working["RMSE"] = pd.to_numeric(working["RMSE"], errors="coerce")
    working["Trials"] = pd.to_numeric(working["Trials"], errors="coerce")

    alss_rows = working[working["Mode"].str.lower() != "baseline"].copy()
    alss_rows = alss_rows.dropna(subset=["Tau", "Improvement_%", "Harmlessness_%", "RMSE"])

    grouped = alss_rows.groupby(["Mode", "Tau"], dropna=False)

    summary = grouped.agg(
        Conditions=("Improvement_%", "count"),
        Trials_Per_Condition=("Trials", "max"),
        Mean_Improvement_Pct=("Improvement_%", "mean"),
        Median_Improvement_Pct=("Improvement_%", "median"),
        Worst_Improvement_Pct=("Improvement_%", "min"),
        Best_Improvement_Pct=("Improvement_%", "max"),
        Positive_Improvement_Count=("Improvement_%", lambda values: int((values > 0).sum())),
        Negative_Improvement_Count=("Improvement_%", lambda values: int((values < 0).sum())),
        Average_Harmlessness_Pct=("Harmlessness_%", "mean"),
        Worst_Harmlessness_Pct=("Harmlessness_%", "min"),
        Mean_RMSE=("RMSE", "mean"),
    ).reset_index()

    summary["Positive_Improvement_Rate_Pct"] = (
        100.0 * summary["Positive_Improvement_Count"] / summary["Conditions"]
    )

    worst_penalty = summary["Worst_Improvement_Pct"].clip(upper=0).abs()
    summary["Selection_Score"] = summary["Mean_Improvement_Pct"] - 0.5 * worst_penalty

    summary["Reject_Worst_Degradation"] = (
        summary["Worst_Improvement_Pct"] < worst_degradation_threshold
    )

    summary["Reject_Low_Harmlessness"] = (
        summary["Average_Harmlessness_Pct"] < min_average_harmlessness
    )

    summary["Pass"] = ~(
        summary["Reject_Worst_Degradation"] | summary["Reject_Low_Harmlessness"]
    )

    summary = summary.sort_values(
        by=["Pass", "Selection_Score", "Mean_Improvement_Pct"],
        ascending=[False, False, False],
    ).reset_index(drop=True)

    return summary


def print_summary(summary: pd.DataFrame) -> None:
    display_columns = [
        "Mode",
        "Tau",
        "Conditions",
        "Trials_Per_Condition",
        "Mean_Improvement_Pct",
        "Worst_Improvement_Pct",
        "Average_Harmlessness_Pct",
        "Positive_Improvement_Rate_Pct",
        "Selection_Score",
        "Pass",
    ]

    print("\nALSS parameter-selection summary:")
    print(summary[display_columns].to_string(index=False))

    passing = summary[summary["Pass"]].copy()

    print("\nRecommended decision:")
    if passing.empty:
        print("No candidate passed the robustness filters.")
        print("Do not freeze ALSS parameters yet; refine the algorithm or selection grid.")
        return

    best = passing.iloc[0]
    print(
        "Selected candidate: "
        f"mode={best['Mode']}, "
        f"tau={best['Tau']}, "
        f"score={best['Selection_Score']:.3f}, "
        f"mean improvement={best['Mean_Improvement_Pct']:.3f}%, "
        f"worst improvement={best['Worst_Improvement_Pct']:.3f}%, "
        f"average harmlessness={best['Average_Harmlessness_Pct']:.3f}%"
    )


def main() -> None:
    args = parse_args()

    input_path = Path(args.input).expanduser().resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {input_path}")

    output_path = (
        Path(args.output).expanduser().resolve()
        if args.output
        else input_path.parent / "alss_selection_summary.csv"
    )

    df = pd.read_csv(input_path)
    validate_input(df, input_path)

    summary = summarize_diagnostics(
        df=df,
        worst_degradation_threshold=args.worst_degradation_threshold,
        min_average_harmlessness=args.min_average_harmlessness,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_path, index=False)

    print_summary(summary)

    print("\nSaved summary CSV:")
    print(output_path)


if __name__ == "__main__":
    main()